version: '3'
services:
  dev:
    build:
      context: .
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
